=== api-evangelist/apache-pulsar/json-schema/apache-pulsar-policies-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-pulsar/refs/heads/main/json-schema/apache-pulsar-policies-schema.json",
  "title": "Policies",
  "description": "Policies schema from Apache Pulsar",
  "type": "object",
  "properties": {
    "replication_clusters": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "bundles": {
      "type": "object"
    },
    "retention_policies": {
      "$ref": "#/components/schemas/RetentionPolicies"
    },
    "schema_auto_update_compatibility_strategy": {
      "type": "string"
    },
    "message_ttl_in_seconds": {
      "type": "integer"
    },
    "max_producers_per_topic": {
      "type": "integer"
    },
    "max_consumers_per_topic": {
      "type": "integer"
    },
    "max_consumers_per_subscription": {
      "type": "integer"
    },
    "backlog_quota_map": {
      "type": "object"
    }
  }
}

=== api-evangelist/apache-pulsar/examples/apache-pulsar-policies-example.json
{
  "replication_clusters": [
    "example"
  ],
  "bundles": {},
  "retention_policies": {},
  "schema_auto_update_compatibility_strategy": "2026-04-19T10:00:00Z",
  "message_ttl_in_seconds": 1234,
  "max_producers_per_topic": 1234,
  "max_consumers_per_topic": 1234,
  "max_consumers_per_subscription": 1234,
  "backlog_quota_map": {}
}
