=== api-evangelist/apache-pulsar/json-schema/apache-pulsar-function-config-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-pulsar/refs/heads/main/json-schema/apache-pulsar-function-config-schema.json",
  "title": "FunctionConfig",
  "description": "FunctionConfig schema from Apache Pulsar",
  "type": "object",
  "properties": {
    "tenant": {
      "type": "string"
    },
    "namespace": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "className": {
      "type": "string"
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "output": {
      "type": "string"
    },
    "logTopic": {
      "type": "string"
    },
    "processingGuarantees": {
      "type": "string",
      "enum": [
        "ATLEAST_ONCE",
        "ATMOST_ONCE",
        "EFFECTIVELY_ONCE"
      ]
    },
    "parallelism": {
      "type": "integer"
    },
    "runtime": {
      "type": "string",
      "enum": [
        "JAVA",
        "PYTHON",
        "GO"
      ]
    },
    "autoAck": {
      "type": "boolean"
    },
    "userConfig": {
      "type": "object",
      "additionalProperties": true
    }
  }
}

=== api-evangelist/apache-pulsar/examples/apache-pulsar-function-config-example.json
{
  "tenant": "example",
  "namespace": "example-name",
  "name": "example-name",
  "className": "example-name",
  "inputs": [
    "example"
  ],
  "output": "example",
  "logTopic": "example",
  "processingGuarantees": "ATLEAST_ONCE",
  "parallelism": 1234,
  "runtime": "JAVA",
  "autoAck": true,
  "userConfig": {}
}
