=== api-evangelist/apache-pulsar/json-schema/apache-pulsar-topic-stats-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-pulsar/refs/heads/main/json-schema/apache-pulsar-topic-stats-schema.json",
  "title": "TopicStats",
  "description": "TopicStats schema from Apache Pulsar",
  "type": "object",
  "properties": {
    "msgRateIn": {
      "type": "number"
    },
    "msgRateOut": {
      "type": "number"
    },
    "msgThroughputIn": {
      "type": "number"
    },
    "msgThroughputOut": {
      "type": "number"
    },
    "averageMsgSize": {
      "type": "number"
    },
    "storageSize": {
      "type": "integer"
    },
    "backlogSize": {
      "type": "integer"
    },
    "publishers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "msgRateIn": {
            "type": "number"
          },
          "msgThroughputIn": {
            "type": "number"
          },
          "producerName": {
            "type": "string"
          },
          "producerId": {
            "type": "integer"
          }
        }
      }
    },
    "subscriptions": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "msgRateOut": {
            "type": "number"
          },
          "msgThroughputOut": {
            "type": "number"
          },
          "msgBacklog": {
            "type": "integer"
          },
          "consumers": {
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        }
      }
    }
  }
}

=== api-evangelist/apache-pulsar/examples/apache-pulsar-topic-stats-example.json
{
  "msgRateIn": 0.5,
  "msgRateOut": 0.5,
  "msgThroughputIn": 0.5,
  "msgThroughputOut": 0.5,
  "averageMsgSize": 0.5,
  "storageSize": 1234,
  "backlogSize": 1234,
  "publishers": [
    {
      "msgRateIn": 0.5,
      "msgThroughputIn": 0.5,
      "producerName": "example-name",
      "producerId": 1234
    }
  ],
  "subscriptions": {}
}
